### ISSUE TITLE
Database Setup

### ISSUE THREAD

**Issue by RapidGravy** [kaisjessa/discordbot#1]
Would you be able to release the database json to import into firebase?

Since the bot's offline I've cloned the git and setup firebase and got the bot working but am not sure of the database setup; just keep getting the following:

```
node test.js
(node:30924) ExperimentalWarning: The http2 module is an experimental API.
FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at gotData (/home/discordbots/eventbot/test.js:32:17)
    at /home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/view/EventRegistration.js:65:22
    at Object.exports.exceptionGuard (/home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/util/util.js:556:9)
    at EventList.raise (/home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/view/EventQueue.js:158:24)
    at EventQueue.raiseQueuedEventsMatchingPredicate_ (/home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/view/EventQueue.js:111:41)
    at EventQueue.raiseEventsForChangedPath (/home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/view/EventQueue.js:95:14)
    at Object.onComplete (/home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/Repo.js:116:39)
    at /home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/PersistentConnection.js:189:32
    at PersistentConnection.onDataMessage_ (/home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/PersistentConnection.js:444:17)
/home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/util/util.js:567
            throw e;
            ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at gotData (/home/discordbots/eventbot/test.js:32:17)
    at /home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/view/EventRegistration.js:65:22
    at Object.exports.exceptionGuard (/home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/util/util.js:556:9)
    at EventList.raise (/home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/view/EventQueue.js:158:24)
    at EventQueue.raiseQueuedEventsMatchingPredicate_ (/home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/view/EventQueue.js:111:41)
    at EventQueue.raiseEventsForChangedPath (/home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/view/EventQueue.js:95:14)
    at Object.onComplete (/home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/Repo.js:116:39)
    at /home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/PersistentConnection.js:189:32
    at PersistentConnection.onDataMessage_ (/home/discordbots/eventbot/node_modules/@firebase/database/dist/cjs/src/core/PersistentConnection.js:444:17)
```
`

**Comment by Rastagang** [comment]
Would love to see this aswell.
